<a href="https://colab.research.google.com/github/groupsvkg/ai/blob/main/numpy_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

a = np.array([2, 5, 6, 9])
b = np.array([3.9, 4, 6, 8])
print(a*b)
print(a+b)
print(np.sin(a))

[ 7.8 20.  36.  72. ]
[ 5.9  9.  12.  17. ]
[ 0.90929743 -0.95892427 -0.2794155   0.41211849]


In [17]:
a = np.arange(25).reshape(5,5)

print(a)

# Print Corners
## Corners
print(a[0::4, 0::4])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  4]
 [20 24]]
